// ------------------------------------------------ My trades tab
async function saveFile(name,text,btn){try{const dl=await window.claude?.use?.("downloads");if(!dl){btn.hidden=true;return}await dl.save({filename:name,data:text})}catch(e){}}
const csvOf=rows=>rows.map(r=>r.map(v=>{const s=v==null?"":String(v);return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}).join(",")).join("\n");
window.claude?.use?.("downloads").then(dl=>{if(dl)$("dl-jour").hidden=false}).catch(()=>{});
function stats(list){const pn=list.map(r=>r.pnl),Rs=list.map(r=>r.R).filter(isF),w=pn.filter(v=>v>0),sl=pn.filter(v=>v<=0).reduce((a,b)=>a+b,0);
 return {n:list.length,win:list.length?w.length/list.length:NaN,avgR:Rs.length?Rs.reduce((a,b)=>a+b,0)/Rs.length:NaN,pnl:pn.reduce((a,b)=>a+b,0),pf:sl<0?w.reduce((a,b)=>a+b,0)/-sl:NaN,hold:list.length?list.reduce((a,r)=>a+r.bars,0)/list.length:NaN}}
function drawMine(){
 const K=(l,v,n="",c="")=>`<div class="k"><div class="lab">${l}</div><div class="v ${c}">${v}</div><div class="note">${n}</div></div>`,a=account(),ret=a.eq/a.start-1;
 $("acct-k").innerHTML=K(`${mode()} equity`,money(a.eq),`started ${money(a.start)}`)+K("Return",spct(ret,2),"",ret>0?"pos":ret<0?"neg":"")+K("Open P&L",smoney(a.unreal),"",a.unreal>0?"pos":a.unreal<0?"neg":"")+K("Closed P&L",smoney(a.real),"",a.real>0?"pos":a.real<0?"neg":"")+K("Open positions",a.open)+K("Exposure",pct(a.expo/a.eq,0));
 const open=simAll().filter(r=>r.status==="open"||r.status==="pending");
 $("pos-t").innerHTML="<tr>"+["symbol","side","shares","placed","entry","last","stop","target","bars","P&L","R",""].map(h=>`<th>${h}</th>`).join("")+"</tr>"+(open.length?open.map(r=>{const lv=levelsAt(r.o,uptoFor(r.o)+1),dd=DS[r.o.sym];
  return `<tr><td>${esc(r.o.sym)}</td><td class="${r.o.side>0?"up":"down"}">${r.o.side>0?"long":"short"}</td><td>${r.o.qty.toLocaleString()}</td><td>${r.o.date}</td><td>${r.status==="pending"?'<span class="acc">pending</span>':fp(r.entryPx)}</td><td>${fp(dd.c[uptoFor(r.o)])}</td><td>${fp(lv.stop)}</td><td>${fp(lv.target)}</td><td>${r.bars??"—"}</td><td class="${cl(r.upnl)}">${r.status==="open"?smoney(r.upnl):"—"}</td><td class="${cl(r.R)}">${r.status==="open"?sR(r.R):"—"}</td>
  <td>${r.status==="open"?`<button class="x" data-be="${r.o.id}" title="Move the stop to the entry price">stop → entry</button> <button class="x" data-close="${r.o.id}">${r.closing?"closing…":"close"}</button>`:`<button class="x" data-cancel="${r.o.id}">cancel</button>`}</td></tr>`}).join(""):`<tr><td colspan="12" class="note" style="text-align:left">No open ${mode()} positions. Use the order ticket next to the chart.</td></tr>`);
 const jour=ORDERS.map(o=>simulate(o,uptoFor(o))).filter(r=>r.status==="closed").sort((x,y)=>(DS[y.o.sym]?.d[y.exitIdx]||"").localeCompare(DS[x.o.sym]?.d[x.exitIdx]||""));
 $("jour-t").innerHTML="<tr>"+["symbol","mode","side","shares","entry date","entry","exit date","exit","reason","bars","P&L","R","system said","note"].map(h=>`<th>${h}</th>`).join("")+"</tr>"+(jour.length?jour.map(r=>{const dd=DS[r.o.sym],sy=r.o.sys;
  return `<tr data-go="${r.o.id}"><td>${esc(r.o.sym)}</td><td><span class="tag ${r.o.mode==="replay"?"r":"l"}">${r.o.mode}</span></td><td class="${r.o.side>0?"up":"down"}">${r.o.side>0?"long":"short"}</td><td>${r.o.qty.toLocaleString()}</td><td>${dd.d[r.entryIdx]}</td><td>${fp(r.entryPx)}</td><td>${dd.d[r.exitIdx]}</td><td>${fp(r.exitPx)}</td><td>${r.reason}</td><td>${r.bars}</td><td class="${cl(r.pnl)}">${smoney(r.pnl)}</td><td class="${cl(r.R)}">${sR(r.R)}</td><td>${sy?(sy.sig?"signal":sy.setup?`setup, ${THIRD_NAME[thirdOf(sy.score)]||""}`:"no setup"):"—"}</td><td style="text-align:left;white-space:normal;min-width:120px">${esc(r.o.note||"")}</td></tr>`}).join(""):`<tr><td colspan="14" class="note" style="text-align:left">Closed paper trades appear here, with results in dollars and in R (multiples of the amount risked).</td></tr>`);
 $("dl-jour").onclick=e=>saveFile("paper-journal.csv",csvOf([["symbol","mode","side","shares","entry_date","entry","exit_date","exit","reason","bars","pnl","R","note"],...jour.map(r=>[r.o.sym,r.o.mode,r.o.side>0?"long":"short",r.o.qty,DS[r.o.sym].d[r.entryIdx],r.entryPx,DS[r.o.sym].d[r.exitIdx],r.exitPx,r.reason,r.bars,r.pnl.toFixed(2),isF(r.R)?r.R.toFixed(3):"",r.o.note||""])]),e.target);
 const blk=(t,s)=>`<div class="lab" style="margin:8px 0 4px">${t}</div><div class="kpis">${K("Trades",s.n)}${K("Win rate",pct(s.win,0))}${K("Avg result",sR(s.avgR),"per trade",s.avgR>0?"pos":s.avgR<0?"neg":"")}${K("Net P&L",smoney(s.pnl))}${K("Profit factor",fmt(s.pf,2))}${K("Avg hold",isF(s.hold)?s.hold.toFixed(1)+" bars":"—")}</div>`;
 const all=stats(jour);const ban=jour.length<30?`<div class="ban mid">${jour.length} closed trade${jour.length===1?"":"s"}. Results start to mean something after about 30.</div>`:`<div class="ban ${all.avgR>.1?"good":all.avgR>0?"mid":"bad"}">Your trades average ${sR(all.avgR)} over ${jour.length} trades.</div>`;
 const sys=RES?stats(RES.bt.trades.map(t=>({pnl:t.pnl,R:t.R,bars:t.bars_held}))):null;
 $("mystats").innerHTML=ban+blk("Replay practice",stats(jour.filter(r=>r.o.mode==="replay")))+blk("Live paper trades",stats(jour.filter(r=>r.o.mode==="live")))+(sys?blk("System (walk-forward backtest, all symbols)",sys):"")}
$("pos-t").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;const o=ORDERS.find(x=>x.id===(b.dataset.close||b.dataset.cancel||b.dataset.be));if(!o)return;
 const d=DS[o.sym],c=REPLAY&&REPLAY.sym===o.sym?REPLAY.idx:d.d.length-1;
 if(b.dataset.cancel)o.cancelled=true;if(b.dataset.close&&!o.closeDate){o.closeDate=d.d[c];o.closeFill=ACCT().fill}
 if(b.dataset.be){const r=simulate(o,c);if(r.status==="open")setLevel(o,"stop",r.entryPx,false)}saveOrders();renderLive();annotate()});
$("jour-t").addEventListener("click",e=>{const tr=e.target.closest("tr[data-go]");if(!tr||REPLAY)return;const o=ORDERS.find(x=>x.id===tr.dataset.go);if(o)focusDate(o.sym,o.date)});
$("reset-replay").addEventListener("click",e=>armed(e.target,()=>{ORDERS=ORDERS.filter(o=>o.mode!=="replay");saveOrders();renderLive();annotate()}));
$("reset-all").addEventListener("click",e=>armed(e.target,()=>{ORDERS=[];saveOrders();renderLive();annotate()}));

// ------------------------------------------------ Volatility tab
function lastGarch(s,i){let g=null;for(const x of s.garchSteps)if(x.i<=i)g=x;return g}
function garchTerm(s,i,H=60){const g=lastGarch(s,i);if(!g||!isF(s.garch[i]))return null;const s2=s.garch[i]**2/252,VL=g.pers<1?g.omega/(1-g.pers):s2,out=[];let acc=0;
 for(let h=1;h<=H;h++){acc+=VL+Math.pow(g.pers,h-1)*(s2-VL);out.push(Math.sqrt(acc/h*252))}return {g,term:out,VL:Math.sqrt(VL*252)}}
function drawVol(){
 const s=S();if(!s){["vol-k","vol-say"].forEach(id=>$(id).innerHTML="");["v-est","v-cone","v-term","v-move","v-dist","v-tails","v-acf","v-fc","v-use"].forEach(id=>needRun(id));return}
 if(!$("v-est")._fullLayout)$("v-est").innerHTML="";const i=st.pinned&&st.cursor!=null?Math.min(st.cursor,cur()):cur(),c=s.c[i],K=(l,v,n="",x="")=>`<div class="k"><div class="lab">${l}</div><div class="v ${x}">${v}</div><div class="note">${n}</div></div>`;
 const GT=garchTerm(s,i),r=s.r.slice(1,i+1).filter(isF),N=r.length;
 const vov=(()=>{const a=[];for(let k=Math.max(25,i-60);k<=i;k++)if(isF(s.yz20[k])&&isF(s.yz20[k-5]))a.push(Math.log(s.yz20[k]/s.yz20[k-5]));if(a.length<10)return NaN;const m=a.reduce((x,y)=>x+y,0)/a.length;return Math.sqrt(a.reduce((x,y)=>x+(y-m)**2,0)/(a.length-1))})();
 $("vol-k").innerHTML=K("Yang-Zhang 20d",fmt(s.yz20[i],1)+"%","most efficient OHLC estimator")+K("GARCH next day",fmt(s.garch[i],1)+"%",GT?`long-run ${fmt(GT.VL,1)}%`:"needs 500 bars")+K("HAR 5-day",fmt(s.har5[i],1)+"%","forecast")+
  K("Vol rank",pct(s.vrank[i],0),"vs this stock's 2 years")+K("Vol trend",isF(s.vterm[i])?(s.vterm[i]>0?"rising":"falling"):"—",`5d ${fmt(s.yz5[i],0)}% vs 60d ${fmt(s.yz60[i],0)}%`)+
  K("Persistence",GT?fmt(GT.g.pers,3):"—",GT?`shock half-life ${fmt(GT.g.half,0)} days`:"")+K("Vol of vol",isF(vov)?pct(vov,0):"—","std of 5-day log change")+K("VIX",fmt(s.vix[i],1),`rank ${pct(s.frank[i],0)}`)+K("ATR",fp(s.atr[i]),pct(s.atr[i]/c,1)+" of price");
 const hi=s.vrank[i]>.66,lo=s.vrank[i]<.33,rising=s.vterm[i]>0;
 $("vol-say").className="ban "+(hi&&rising?"good":lo&&!rising?"bad":"mid");
 $("vol-say").innerHTML=`<b>${hi?"High":lo?"Low":"Normal"} and ${rising?"rising":"falling"} volatility</b> for ${esc(st.sym)} on ${s.d[i]}. `+(hi||rising?"Within RSI(2) setups, high and rising volatility went with bigger bounces in all three research samples (stress is when liquidity providers are paid most).":"Quiet, falling volatility went with smaller bounces in the research; setups now carry less edge.")+(isF(s.frank[i])?` Market fear is at the ${pct(s.frank[i],0)} rank of its last two years${s.frank[i]>.66?", which historically made reversals pay more (Nagel 2012).":"."}`:"");
 const lo0=Math.max(0,i-(st.n||i)),x=s.d.slice(lo0,i+1),sl=a=>a.slice(lo0,i+1).map(v=>isF(v)?v:null);
 const base2=(h,ex={})=>base(h,Object.assign({hovermode:"x unified",legend:{orientation:"h",x:0,y:1.08,font:{size:9}},margin:{l:44,r:44,t:26,b:28}},ex));
 Plotly.react("v-est",[["cc20","close-close","#898781",1],["park20","Parkinson","#199e70",1],["gk20","Garman-Klass","#c98500",1],["rs20","Rogers-Satchell","#d55181",1],["yz20","Yang-Zhang","#3987e5",2],["garch","GARCH(1,1)","#fab219",1.6],["har5","HAR 5-day","#c08cff",1.3]].map(([k,n,col,w])=>({x,y:sl(s[k]),name:n,mode:"lines",line:{color:col,width:w},hovertemplate:n+" %{y:.1f}%<extra></extra>"}))
  .concat([{x,y:sl(s.vix),name:"VIX (right)",yaxis:"y2",mode:"lines",line:{color:"rgba(255,255,255,.35)",width:1,dash:"dot"},hovertemplate:"VIX %{y:.1f}<extra></extra>"}]),base2(330,{yaxis:{gridcolor:C.grid,ticksuffix:"%"},yaxis2:{overlaying:"y",side:"right",showgrid:false,tickfont:{color:C.muted,size:9}}}),CFG);
 // cone from close-close vol by horizon, history up to bar i
 const Hs=[5,10,20,40,60,120,250],cone=Hs.map(W=>{const v=[];let sm=0,sq=0;for(let k=1;k<=i;k++){const q=s.r[k];if(!isF(q))continue;sm+=q;sq+=q*q;if(k>W){const o=s.r[k-W];if(isF(o)){sm-=o;sq-=o*o}}if(k>=W){const m=sm/W;v.push(Math.sqrt(Math.max(0,(sq-W*m*m)/(W-1))*252)*100)}}const last=v[v.length-1];v.sort((a,b)=>a-b);return {W,last,q:[0,.1,.25,.5,.75,.9,1].map(p=>quantSortedUI(v,p))}});
 const pcol=["#555","#3987e5","#4fa6ff","#fff","#ff9f9f","#e66767","#555"],pn=["min","10%","25%","median","75%","90%","max"];
 Plotly.react("v-cone",pn.map((n,k)=>({x:Hs,y:cone.map(c0=>c0.q[k]),name:n,mode:"lines",line:{color:pcol[k],width:k===3?2:1,dash:k===0||k===6?"dot":"solid"},hovertemplate:n+" %{y:.0f}%<extra></extra>"})).concat([{x:Hs,y:cone.map(c0=>c0.last),name:"now",mode:"lines+markers",line:{color:"#fab219",width:2},marker:{size:8},hovertemplate:"now %{y:.0f}%<extra></extra>"}]),
  base2(330,{xaxis:{type:"log",tickvals:Hs,title:{text:"window (trading days)",font:{size:10}},gridcolor:C.grid},yaxis:{ticksuffix:"%",gridcolor:C.grid},hovermode:"x"}),CFG);
 if(GT){const hh=[...Array(60).keys()].map(k=>k+1);Plotly.react("v-term",[{x:hh,y:GT.term,name:"GARCH expected avg vol",mode:"lines",line:{color:"#fab219",width:2},hovertemplate:"next %{x} days: %{y:.1f}%<extra></extra>"},{x:[1,60],y:[GT.VL,GT.VL],name:"long-run",mode:"lines",line:{color:"#898781",dash:"dash"}},
   {x:[1,60],y:[s.yz20[i],s.yz20[i]],name:"Yang-Zhang 20d now",mode:"lines",line:{color:"#3987e5",dash:"dot"}},{x:[5],y:[s.har5[i]],name:"HAR 5-day",mode:"markers",marker:{color:"#c08cff",size:10}}],
   base2(330,{xaxis:{title:{text:"horizon (trading days)",font:{size:10}},gridcolor:C.grid},yaxis:{ticksuffix:"%",gridcolor:C.grid},hovermode:"x"}),CFG)}
 else clr("v-term",'<div class="empty">GARCH needs at least 500 daily returns.</div>');
 // expected move table
 const sdH=h=>GT?GT.term[h-1]/100*Math.sqrt(h/252):s.yz20[i]/100*Math.sqrt(h/252);
 const emp=h=>{const a=[];for(let k=h;k<=i;k++)a.push(Math.log(s.c[k]/s.c[k-h]));a.sort((u,v)=>u-v);return [quantSortedUI(a,.05),quantSortedUI(a,.95)]};
 $("v-move").innerHTML=`<table class="em"><tr><th>horizon</th><th>σ</th><th>−2σ</th><th>−1σ</th><th>+1σ</th><th>+2σ</th><th>history 5%–95%</th></tr>`+[1,5,10,20].map(h=>{const sg=sdH(h),e=emp(h);return `<tr><td>${h} day${h>1?"s":""}</td><td>${pct(sg,1)}</td><td class="down">${fp(c*Math.exp(-2*sg))}</td><td class="down">${fp(c*Math.exp(-sg))}</td><td class="up">${fp(c*Math.exp(sg))}</td><td class="up">${fp(c*Math.exp(2*sg))}</td><td>${spct(Math.exp(e[0])-1,1)} / ${spct(Math.exp(e[1])-1,1)}</td></tr>`}).join("")+
  `</table><div class="note" style="margin-top:6px">From ${GT?"the GARCH(1,1) term structure":"Yang-Zhang 20-day volatility"} at ${fp(c)}. The system's ${ECFG.stopATR}-ATR stop is ${fp(ECFG.stopATR*s.atr[i])} away, about ${fmt(ECFG.stopATR*s.atr[i]/c/sdH(5),1)}σ of a 5-day move.</div>`;
 // distribution and tails
 const rr=r.slice(-2000),m=rr.reduce((a,b)=>a+b,0)/rr.length,sd=Math.sqrt(rr.reduce((a,b)=>a+(b-m)**2,0)/(rr.length-1)),sk=rr.reduce((a,b)=>a+((b-m)/sd)**3,0)/rr.length,ku=rr.reduce((a,b)=>a+((b-m)/sd)**4,0)/rr.length-3;
 const srt=rr.slice().sort((a,b)=>a-b),hill=(xs)=>{const k=Math.max(10,Math.floor(xs.length*.05)),t=xs.slice(-k-1),u=t[0];return u>0?1/(t.slice(1).reduce((a,b)=>a+Math.log(b/u),0)/k):NaN};
 const hl=hill(srt.map(v=>-v).filter(v=>v>0).sort((a,b)=>a-b)),hr2=hill(srt.filter(v=>v>0)),q=p=>quantSortedUI(srt,p),es=p=>{const t=srt.slice(0,Math.max(1,Math.floor(p*srt.length)));return t.reduce((a,b)=>a+b,0)/t.length};
 const xs=[...Array(80).keys()].map(k=>m-5*sd+k*10*sd/79),bw=(srt[srt.length-1]-srt[0])/60;
 Plotly.react("v-dist",[{type:"histogram",x:rr,histnorm:"probability density",name:"actual",marker:{color:"rgba(57,135,229,.55)"},nbinsx:80},{x:xs,y:xs.map(v=>Math.exp(-0.5*((v-m)/sd)**2)/(sd*Math.sqrt(2*Math.PI))),name:"normal",mode:"lines",line:{color:"#fab219",width:2}}],
  base2(260,{bargap:0,xaxis:{tickformat:".0%",gridcolor:C.grid},yaxis:{gridcolor:C.grid,title:{text:"density",font:{size:9}}},hovermode:false}),CFG);
 $("v-tails").innerHTML=`<table class="em"><tr><th>last ${rr.length} days</th><th>value</th><th>reading</th></tr><tr><td>skew</td><td>${fmt(sk,2)}</td><td>${sk<-.2?"crashes larger than spikes":sk>.2?"spikes larger than drops":"roughly symmetric"}</td></tr><tr><td>excess kurtosis</td><td>${fmt(ku,1)}</td><td>${ku>3?"fat tails: big days far more common than a normal model says":"moderate tails"}</td></tr>
  <tr><td>Hill tail index (down / up)</td><td>${fmt(hl,1)} / ${fmt(hr2,1)}</td><td>lower = fatter tail; below 4 means very fat</td></tr><tr><td>1-day VaR 95% / 99%</td><td>${pct(-q(.05),1)} / ${pct(-q(.01),1)}</td><td>normal model: ${pct(1.645*sd,1)} / ${pct(2.326*sd,1)}</td></tr><tr><td>expected shortfall 95% / 99%</td><td>${pct(-es(.05),1)} / ${pct(-es(.01),1)}</td><td>average loss on the worst days</td></tr></table>`;
 // clustering + leverage
 const acf=(a,L)=>{const n=a.length,mm=a.reduce((x,y)=>x+y,0)/n,v=a.reduce((x,y)=>x+(y-mm)**2,0);return [...Array(L).keys()].map(k=>{let s0=0;for(let t=k+1;t<n;t++)s0+=(a[t]-mm)*(a[t-k-1]-mm);return s0/v})};
 const L=30,ab=rr.map(Math.abs),lag=[...Array(L).keys()].map(k=>k+1),lev=[...Array(10).keys()].map(k=>{const a=[],b=[];for(let t=0;t+k+1<rr.length;t++){a.push(rr[t]);b.push(Math.abs(rr[t+k+1]))}const ma=a.reduce((x,y)=>x+y,0)/a.length,mb=b.reduce((x,y)=>x+y,0)/b.length;let cv=0,va=0,vb=0;a.forEach((v,j)=>{cv+=(v-ma)*(b[j]-mb);va+=(v-ma)**2;vb+=(b[j]-mb)**2});return cv/Math.sqrt(va*vb)});
 Plotly.react("v-acf",[{x:lag,y:acf(ab,L),name:"|return| (clustering)",type:"bar",marker:{color:"#fab219"}},{x:lag,y:acf(rr,L),name:"return",type:"bar",marker:{color:"#3987e5"}},{x:lag.slice(0,10),y:lev,name:"return → later |return| (leverage)",mode:"lines+markers",line:{color:"#e66767"}},
  {x:[1,L],y:[2/Math.sqrt(rr.length),2/Math.sqrt(rr.length)],mode:"lines",line:{color:"#555",dash:"dot"},name:"noise band",showlegend:false},{x:[1,L],y:[-2/Math.sqrt(rr.length),-2/Math.sqrt(rr.length)],mode:"lines",line:{color:"#555",dash:"dot"},showlegend:false}],
  base2(300,{barmode:"group",xaxis:{title:{text:"lag (days)",font:{size:10}},gridcolor:C.grid},yaxis:{gridcolor:C.grid},hovermode:"x"}),CFG);
 // forecast check: next-5-day realised (OHLC proxy) vs forecasts made at t, only where t+5 <= i
 const fr=[],fg=[],fh=[],fy=[],fd=[];for(let t=Math.max(s.first,lo0);t+5<=i;t++){let a=0,ok=true;for(let k=1;k<=5;k++){if(!isF(s.rv[t+k]))ok=false;a+=s.rv[t+k]}if(!ok)continue;fr.push(Math.sqrt(a/5*252)*100);fg.push(s.garch[t]);fh.push(s.har5[t]);fy.push(s.yz20[t]);fd.push(s.d[t])}
 const err=(f)=>{let se=0,n=0;f.forEach((v,k)=>{if(isF(v)&&fr[k]>0&&v>0){se+=(Math.log(v)-Math.log(fr[k]))**2;n++}});return n?Math.sqrt(se/n):NaN};
 Plotly.react("v-fc",[{x:fd,y:fr,name:"realised next 5 days",mode:"lines",line:{color:"rgba(255,255,255,.55)",width:1}},{x:fd,y:fg,name:`GARCH (log-RMSE ${fmt(err(fg),2)})`,mode:"lines",line:{color:"#fab219",width:1.5}},{x:fd,y:fh,name:`HAR (${fmt(err(fh),2)})`,mode:"lines",line:{color:"#c08cff",width:1.3}},{x:fd,y:fy,name:`YZ20 as forecast (${fmt(err(fy),2)})`,mode:"lines",line:{color:"#3987e5",width:1}}],
  base2(300,{yaxis:{ticksuffix:"%",gridcolor:C.grid,type:"log"}}),CFG);
 $("v-use").innerHTML=`<p><b>Stops.</b> The system stop is ${ECFG.stopATR} ATR (${fp(ECFG.stopATR*s.atr[i])}). That is ${fmt(ECFG.stopATR*s.atr[i]/c/sdH(5),1)} five-day standard deviations, so ordinary noise rarely reaches it. When volatility jumps, ATR widens with it, so the stop keeps the same meaning.</p>
  <p><b>Size.</b> Risking ${$("t-risk").value}% of equity with that stop means about <b>${pct(+$("t-risk").value/100/(ECFG.stopATR*s.atr[i]/c),0)}</b> of equity in the position. Higher volatility automatically means a smaller position.</p>
  <p><b>Setup quality.</b> Rising volatility (5-day above 60-day) and a high volatility rank both carry positive weight in the Reversal Edge Score. Today they read <b>${isF(s.vterm[i])?(s.vterm[i]>0?"rising":"falling"):"—"}</b> and <b>${pct(s.vrank[i],0)}</b>.</p>
  <p><b>Which forecast to trust.</b> Lower log-RMSE in the forecast check is better. GARCH reacts fastest to shocks; HAR blends day, week and month and is usually steadiest; Yang-Zhang is the best measure of what already happened.</p>`}

// ------------------------------------------------ Model tab extras: weights, evidence, results by third
function drawEdge(){const el=$("edgebox");if(!el)return;const s=S();if(!RES||!s){el.innerHTML="";return}
 const i=cur(),stp=lastStep(s,i),w0=RES.prior.w;
 el.innerHTML=`<h2>${esc(st.sym)} · Reversal Edge weights and evidence</h2><div class="tw"><table class="bl"><tr><th>sign</th><th>family</th><th>research weight</th><th>weight now</th><th>87 stocks Δ</th><th>TSLA 11-17 Δ</th><th>TSLA 18-26 Δ</th><th style="text-align:left">meaning</th></tr>`+
  RES.signs.map((g,k)=>`<tr><td>${esc(g[1])}</td><td>${esc(g[2])}</td><td>${fmt(w0[g[0]],2)}</td><td>${stp?fmt(stp.coef[k],2):"—"}</td>${g[4].map(v=>`<td class="${cl(v)}">${v>0?"+":""}${v} bp</td>`).join("")}<td style="text-align:left;white-space:normal;min-width:260px">${esc(g[3])}</td></tr>`).join("")+`</table></div>
  <div class="note" style="margin:6px 0 14px">Δ = average trade of RSI(2)&lt;10 setups in the top third of that sign minus the bottom third. Every kept sign points the same way in all three samples; signs that flipped (z-score depth, trend, 5-day drop, close location) were left out. Gap and lower wick count against the trade.</div>
  <h2>Results by score third</h2><div class="tw"><table class="bl"><tr><th>score third</th><th>87 stocks: avg trade</th><th>87 stocks: won</th><th>TSLA (unseen): avg trade</th><th>TSLA: won</th><th>${esc(st.sym)} so far: trades</th><th>avg trade</th><th>won</th></tr>`+
  [0,1,2].map(k=>`<tr><td style="color:${THIRD_COL[k]}">${THIRD_NAME[k]}</td><td class="${cl(RESEARCH_THIRDS.avg87[k])}">${(RESEARCH_THIRDS.avg87[k]/100).toFixed(2)}%</td><td>${pct(RESEARCH_THIRDS.win87[k],0)}</td><td class="${cl(RESEARCH_THIRDS.avgT[k])}">${(RESEARCH_THIRDS.avgT[k]/100).toFixed(2)}%</td><td>${pct(RESEARCH_THIRDS.winT[k],0)}</td><td>${stp?stp.thirds[k].n:"—"}</td><td class="${cl(stp&&stp.thirds[k].avg)}">${stp?spct(stp.thirds[k].avg,2):"—"}</td><td>${stp?pct(stp.thirds[k].win,0):"—"}</td></tr>`).join("")+`</table></div>
  <div class="note" style="margin-top:6px">Trades: RSI(2)&lt;10 setup, buy next open, exit on the first close above the 5-day average, 3-ATR stop or 10 bars, 10 bp round-trip cost. The ${esc(st.sym)} column counts only setups resolved before the latest refit.</div>`}
